language: bash

services: 
  - docker

script:
  - docker build -t android-build-box .

after_script:
  - docker images

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
